### ISSUE TITLE
Cannot build pretixscan on M1 Mac: protoc-gen-javalite-3.0.0-osx-aarch_64.exe missing

### ISSUE THREAD

**Issue by biafra23** [pretix/libpretixsync#12]
https://github.com/pretix/libpretixsync/blob/master/libpretixsync/build.gradle references `com.google.protobuf:protoc-gen-javalite:3.0.0` for which there is no m1 binary at https://repo.maven.apache.org/maven2/com/google/protobuf/protoc-gen-javalite/3.0.0/protoc-gen-javalite-3.0.0-osx-aarch_64.exe

How do I resolve this?

**Comment by raphaelm** [comment]
Are you trying to build pretixSCAN Android or pretixSCAN Desktop?

In case of pretixSCAN Android, maybe @robbi5 can help.

In case of pretixSCAN Desktop I think you're on your own right now, it has never been run on macOS before since we only publish Windows and Linux builds.

**Comment by robbi5** [comment]
I have a prelimitary, untested and uncommited patch here to build libpretixsync on m1 (aarch64): https://gist.github.com/robbi5/33bfcdb72e522e8f843c1986598ee286

For my current day-to-day tests it works, but I need to take a deeper look if something in the protobuf usage breaks with it before opening a pull request :)

**Comment by raphaelm** [comment]
If the tests pass, I'd be very confident that it is fine, our protobuf usage is very simplistic
