### ISSUE TITLE
Missing Files in libpretixsync

### ISSUE THREAD

**Issue by Bex230** [pretix/libpretixsync#37]
Dear Team at Pretix,

I trust this message reaches you in good spirits. I wanted to start by thanking you for creating such exceptional software. The Community version has truly improved my workflow and I am thankful for that.

I did come across a small problem that I wanted to discuss with you. It seems like there are a few files missing from the libpretixsync folder. Would you be able to help me out with this? Your assistance would be greatly appreciated.

Sincerly

Rebka Mesfin

**Comment by raphaelm** [comment]
Hi Rebka,

could you clarify what files are missing and why you think they are missing?

**Comment by Bex230** [comment]
Files found in db mostly they are mentioned as an import but cant find them anywhere in the folder

import eu.pretix.libpretixsync.db.Item;
import eu.pretix.libpretixsync.db.Question;
import eu.pretix.libpretixsync.db.QueuedCheckIn;
import eu.pretix.libpretixsync.db.Models;
import eu.pretix.libpretixsync.Models;

The above are a few of the mentioned

**Comment by raphaelm** [comment]
They are auto-generated during build

**Comment by Bex230** [comment]
Thanks
